import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  SignIn,
  SignInButton,
  SignOutButton,
  useUser,
} from "@clerk/clerk-react";

import { api } from "~/utils/api";
import { useEffect } from "react";

const Home: NextPage = () => {
  const user = useUser();
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    if (user.isSignedIn) {
      console.log("User id: ", user.user?.id);
      // const data = api.user.getUserInfo.useQuery({ userId: user.user?.id! });
      // console.log("User data: ", data);
    }
  }, [user.isSignedIn]);

  return (
    <>
      <Head>
        <title>So What Happended</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e7dbe] to-[#0d0e32]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
      </main>
    </>
  );
};

export default Home;
